spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: yeppi0101
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer:
      datasource:
        initialization: true

  sql:
    init:
      mode: always


jwt:
  header: Authorization
  token-validity-in-seconds: 3600
